core/urls.py
from django.urls import path
from .views import square_of_a
app_name = "core"


urlpatterns = [
    path('square_of_a', square_of_a)
]

soaqaz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include("core.urls")),
    path('', include("web.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
]

web/urls.py
from django.urls import path
from .views import PanCreateView, PanUpdateView, PanDeleteView, profile_view, RegisterView, index, WebPasswordResetView

app_name = "web"

urlpatterns = [
    path('index', index, name="index"),
    path('pans', PanCreateView.as_view(), name="create_pan"),
    path('pans/<pk>', PanUpdateView.as_view(), name="update_pan"),
    path('pans/<pk>/delete', PanDeleteView.as_view(), name="delete_pan"),
    path('profile', profile_view, name="profile"),
    path('', RegisterView.as_view(), name="register"),
    path("password_reset/", WebPasswordResetView.as_view(), name="password_reset"),
]

core/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.fields import GenericRelation, GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


# Создадим модель нашего покупателя, просто унаследовав пользователя Django
from django.urls import reverse


class Buyer(AbstractUser):
    ...


class PriceMixin(models.Model):
    """
        Абстрактная родительская таблица для общих полей и методов, чтобы не повторяться
    """
    price = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        abstract = True


class Pan(PriceMixin):
    """
        Модель описывающая таблицу с товаром типа: Сковорода
    """
    VENDOR_TEFAL = "tefal", "Tefal"
    VENDOR_FISSMAN = "fissman", "Fissman"

    vendor_choices = [(VENDOR_TEFAL[0], VENDOR_TEFAL[1]),
                      (VENDOR_FISSMAN[0], VENDOR_FISSMAN[1])]
    vendor = models.CharField(max_length=128, choices=vendor_choices)
    diameter = models.PositiveIntegerField()

    purchases = GenericRelation("Purchase", related_query_name="pan", related_name="pans")

    def __str__(self):
        return f"Сковорода фирмы: {self.get_vendor_display()}, {self.diameter} sm"

    def get_absolute_url(self):
        return reverse("web:update_pan", args=[self.id])

class Potato(PriceMixin):
    """
        Модель описывающая таблицу с товаром типа: Картофель
    """

    COUNTRY_BEL = "bel", "Беларусь"
    COUNTRY_RUS = "rus", "Россия"
    country_choices = [(COUNTRY_BEL[0], COUNTRY_BEL[1]),
                       (COUNTRY_RUS[0], COUNTRY_RUS[1])]

    id = models.CharField(max_length=128, primary_key=True, default=uuid.uuid4())
    country = models.CharField(max_length=128, choices=country_choices)

    purchases = GenericRelation("Purchase", related_query_name="potato")

    def __str__(self):
        return f"Картофель из страны: {self.get_country_display()}"


class Purchase(models.Model):
    """
        Объект описывающий сущность покуаки чего либо.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    count = models.DecimalField(decimal_places=2, max_digits=4,
                                validators=[MinValueValidator(0.01), MaxValueValidator(10000)])
    order = models.ForeignKey("Order", on_delete=models.CASCADE, related_name="purchases")

    # Согласно документации, создаём поля для хранения ContentType и object_id
    # https://docs.djangoproject.com/en/3.2/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericForeignKey
    content_type = models.ForeignKey(ContentType, on_delete=models.RESTRICT)
    object_id = models.CharField(max_length=128)

    # Создаём генерируемый внешний ключ, который может быть связан с продуктами разных типов: сковорода, картошка и тд
    product = GenericForeignKey("content_type", "object_id")

    def __str__(self):
        # кстати тут у нас явный пример полиморфизма, у всех продуктов будет вызван метод __str__, но вернётся разный
        # результат для каждого продукта
        return f"purchase_id: {self.id}, product: {self.product}"

    @property
    def cost(self):
        """
            Возсращает стоимость покупки
        :return: float
        """
        return self.count * self.product.price


class Order(models.Model):
    """
        Модель описывающая заказ, содержит связь с покупками, через related_name="purchases", см core/models.py:52
    """
    buyer = models.ForeignKey(Buyer, on_delete=models.CASCADE, related_name="orders")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Покупатель: {self.buyer.username}, количество товаров в чеке: {self.purchases.count()}"

web/models.py
from django.db import models

# Create your models here.

web/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordResetForm
from django.core.exceptions import ValidationError

from core.models import Pan, Buyer


class PanForm(forms.ModelForm):
    class Meta:
        model = Pan
        fields = ["price", "vendor", "diameter"]


class PanConfirmDelete(forms.Form):
    confirm_delete = forms.BooleanField(required=False)

    def clean(self):
        if self.cleaned_data["confirm_delete"] is False:
            raise ValidationError("You must confirm this form!")
        return super(PanConfirmDelete, self).clean()


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Buyer
        fields = UserCreationForm.Meta.fields + ("email", )

core/views.py
from django.http import HttpResponse


# Create your views here.
from rest_framework.generics import get_object_or_404
from rest_framework.viewsets import ViewSet

from core.models import Buyer
from core.serializers import UserViewSetInputSerializer


def square_of_a(request):
    a = request.GET.get("a")
    if str(a).isdigit():
        return HttpResponse(content=f"Aaa in square is {int(a) ** 2}")
    return HttpResponse(content=f"Aaa is not a digit, or not presented")


class UserViewSet(ViewSet):
    def purchases(self, request):
        params_serializer = UserViewSetInputSerializer(data=request.query_params)
        params_serializer.is_valid(raise_exception=True)

        user_id = params_serializer.validated_data["user_id"]

        user = get_object_or_404(Buyer, pk=user_id)

        # purchases = user.

web/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordResetView
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView

from core.models import Pan, Buyer
from web.forms import PanConfirmDelete, RegisterForm


class PanCreateView(CreateView):
    model = Pan
    fields = ["price", "vendor", "diameter"]

class PanUpdateView(UpdateView):
    model = Pan
    fields = ["price", "vendor"]
    template_name_suffix = '_update_form'


class PanDeleteView(DeleteView):
    model = Pan
    success_url = reverse_lazy('web:create_pan')
    form_class = PanConfirmDelete


@login_required
def profile_view(request):
    return render(request, 'web/profile.html')


class RegisterView(FormView):
    form_class = RegisterForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy("web:profile")
    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


def index(request):
    return render(request, 'web/index.html')


class WebPasswordResetView(PasswordResetView):
    template_name = 'web/password_reset_email.html'

web/templates/core/pan_confirm_delete.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Delete">
</form>

web/templates/core/pan_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message">
</form>

web/templates/core/pan_update_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Youtube project</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
{%  block body %}
{% endblock %}
</body>
</html>

web/templates/web/index.html
{%  extends 'web/base.html' %}

{%  block body %}

        <div class="card" style="width: 30%; margin: 10% auto auto;">
        <div class="card-body" style="background-color: #2aabd2; border-color: #1A01CC">
            <div class="row" >
                <div class="col">
                    <button onclick="document.location.href='{% url "web:profile" %}'">Profile</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

web/templates/web/password_reset_email.html
{% extends 'web/base.html' %}

{%  block body %}
    <h1>СБРОС ПАРОЛЯ</h1>
    <form method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">SUBMIT</button>
    </form>

{% endblock %}

web/templates/web/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <title>Profile</title>
</head>
<body>
    <div class="container mt-5 d-flex justify-content-center">

                <div class="card p-3">

                    <div class="d-flex align-items-center">

                        <div class="image">
                    <img src="https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=80" class="rounded" width="155" >
                    </div>

                    <div class="ml-3 w-100">

                       <h4 class="mb-0 mt-0">{{ user.username }}</h4>
                       <span>Senior Journalist</span>

                       <div class="p-2 mt-2 bg-primary d-flex justify-content-between rounded text-white stats">

                        <div class="d-flex flex-column">

                            <span class="articles">Articles</span>
                            <span class="number1">38</span>

                        </div>

                        <div class="d-flex flex-column">

                            <span class="followers">Followers</span>
                            <span class="number2">980</span>

                        </div>


                        <div class="d-flex flex-column">

                            <span class="rating">Rating</span>
                            <span class="number3">8.9</span>

                        </div>

                       </div>


                       <div class="button mt-2 d-flex flex-row align-items-center">

                        <button class="btn btn-sm btn-outline-primary w-100" onclick="location.href='{% url 'password_change' %}'">Change password</button>
                        <button class="btn btn-sm btn-primary w-100 ml-2" onclick="location.href='{% url 'logout' %}?next={% url 'web:index' %}'">Logout</button>


                       </div>


                    </div>


                    </div>

                </div>

             </div>
</body>
</html>